name: 'partner_portal'
version: '1.0.0'
config-version: 1

require-dbt-version: [">=0.17.0"]

profile: 'partner_portal'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

quoting:
  database: false
  identifier: false
  schema: false

models:
  transient: true
  inputs:
    staging:
        +materialized: view